<<word.cloud, echo=FALSE>>=

library(tm)

go.word.cloud <- function (terms1, terms2, all, lab, tit){
  one.termtable <- terms1[, c("descr", "over_represented_pvalue", "count")]
  names(one.termtable) <- c("term", "p.value.1", "freq.one")
  two.termtable <- terms2[, c("descr", "over_represented_pvalue", "count")]
  names(two.termtable) <- c("term", "p.value.2", "freq.two")
  term.df<- merge(one.termtable, two.termtable, all=all)
  term.df[is.na(term.df$freq.one), "freq.one"] <- 0
  term.df[is.na(term.df$freq.two), "freq.two"] <- 0
  term.df<-transform(term.df, freq.dif = freq.one-freq.two)
  term.df$p.value <- ifelse(term.df$freq.dif<0, term.df$p.value.2,
                            term.df$p.value.1)

  mi <- min(term.df$freq.dif)
  ma <- max(term.df$freq.dif)
  m <- mean(c(mi,ma))
  
  term.df <- term.df[order(term.df$freq.dif),]
  ## the occurence of the frequence difference
  occ <- rle(term.df$freq.dif)$length
  ## equal spread between min and may
  term.df$Spacing <- unlist(sapply(occ,
                                   function(x) seq(mi, ma, length=x)))
  ## patch the values where only one thing was there with mean
  term.df[term.df$Spacing==mi, "Spacing"] <- m

  ## break long names
   term.df$term <- sub("(\\w{12,}) ", "\\1\n",  term.df$term)
  
  term.cloud<-ggplot(term.df, aes(x=freq.dif, y=Spacing)) +
    geom_text(aes(size=freq.one, label=term, colour=p.value)) +
      scale_size(to=c(3,11),
                 name="GO-annotation Frequency") +
                   scale_colour_gradient("p-value for overrepresentation",
                                         breaks=c(0.001, 0.01, 0.02, 0.03, 0.04),
                                         low="darkred",
                                         high="darkblue"
                                         )
  ## aesthetic corrections
  term.cloud <- term.cloud +
    scale_x_continuous(breaks=c(mi, 0, ma), labels=rev(lab))

  ## aesthetic corrections
  term.cloud <- term.cloud + 
    scale_y_continuous(breaks=c(0),
                       labels=c("")) +
                         xlab("") +
                           ylab("")+
                             theme_bw()+
                               opts(panel.grid.major=theme_blank(),
                                    panel.grid.minor=theme_blank(),
                                    title=tit)
 return(term.cloud)
}

GO.op <- GO.over.pop[!duplicated(GO.over.pop$category), ]
GO.oe <- GO.over.eel[!duplicated(GO.over.eel$category), ]

go.eel.vs.pop.mf <- go.word.cloud(GO.op[GO.op$pcf%in%"MF",],
                                  GO.oe[GO.oe$pcf%in%"MF", ],
                                  all=FALSE, c("Enriched more in population differences",
                                    "\nEnriched equally",
                                    "Enriched more in host-species differences"),
                                  "Frequency of enriched molecular function GO-terms for nematode-population vs. host-species")

ggsave("/home/ele/thesis/experimental_infection/figures/word_cloud_eel_vs_pop_mf.png", go.eel.vs.pop.mf, width=22, height=8)


go.eel.vs.pop.bp <- go.word.cloud(GO.op[GO.op$pcf%in%"BP", ],
                                  GO.oe[GO.oe$pcf%in%"BP", ],
                               all=FALSE,
                                  lab=c("Enriched more in population differences",
                                    "Enriched equally",
                                    "Enriched more in host-species differences"),
                                  tit="Frequency of enriched GO-annotation terms for nematode-population vs. host-bspecies differences")

ggsave("/home/ele/thesis/experimental_infection/figures/word_cloud_eel_vs_pop_bp.png", go.eel.vs.pop.bp, width=22, height=8)

go.eel.vs.pop.cc <- go.word.cloud(GO.op[GO.op$pcf%in%"CC", ],
                                  GO.oe[GO.oe$pcf%in%"CC", ],
                                  all=FALSE,
                                  lab=c("Enriched more in population differences",
                                    "\nEnriched equally",
                                    "Enriched more in host-species differences"),
                                  tit="Frequency of enriched GO-annotation terms for nematode-population vs. host-species differences")

ggsave("/home/ele/thesis/experimental_infection/figures/word_cloud_eel_vs_pop_cc.png", go.eel.vs.pop.cc, width=22, height=8)


@ 
