<<DESeq, echo=FALSE, cache=TRUE>>=
sex.conds <- factor(ifelse(grepl("M$", names(counts.frame)), "male", "female" ))
eel.conds <- factor(ifelse(grepl("^AA", names(counts.frame)), "Aa", "Aj" ))
pop.conds <- factor(ifelse(grepl("\\w\\w_R.*", names(counts.frame)), "EU", "TW" ))


## Male/Female

cds.mf <- newCountDataSet(co.f, sex.conds)
cds.mf <- estimateSizeFactors(cds.mf)
cds.mf <- estimateVarianceFunctions(cds.mf)
res.mf <- nbinomTest(cds.mf, "male", "female")

vsd <- getVarianceStabilizedData( cds.mf )
dists <- dist( t( vsd ) )
idists <- as.matrix(dists)

sig.mf <- res.mf[res.mf$padj < .01 & !is.na(res.mf$padj),"id"]

## Eel

cds.eel <- newCountDataSet(co.f, eel.conds)
cds.eel <- estimateSizeFactors(cds.eel)
cds.eel <- estimateVarianceFunctions(cds.eel)
res.eel <- nbinomTest(cds.eel, "Aa", "Aj")

sig.eel <- res.eel[res.eel$padj < .01 & !is.na(res.eel$padj),"id"]

## Populations

cds.pop <- newCountDataSet(co.f, pop.conds)
cds.pop <- estimateSizeFactors(cds.pop)
cds.pop <- estimateVarianceFunctions(cds.pop)
res.pop <- nbinomTest(cds.pop, "EU", "TW")

sig.pop <- res.pop[res.pop$padj < .01 & !is.na(res.pop$padj),"id"]

@ 

<<DESeq.plots, echo=FALSE, results=hide>>=
## check that m/f are clustering, etc...
png("../figures/heat_rep.png", width=720, height=720)
heatmap (idists , symm=TRUE, margins = c (7,7))
dev.off()

## Worm Sex

## scvPlot(cds.mf)

## residualsEcdfPlot( cds.mf, "male" )
## residualsEcdfPlot( cds.mf, "female" )

## plot( 
##      res.mf$baseMean, 
##      res.mf$log2FoldChange, 
##      log="x", pch=20, cex=.4, 
##      col = ifelse( res.mf$padj < .01, "red", "black" ),
##      main="My data")

## Eel species

## scvPlot(cds.eel)

## residualsEcdfPlot( cds.eel, "Aa" )
## residualsEcdfPlot( cds.eel, "Aj" )

## plot( 
##      res.eel$baseMean, 
##      res.eel$log2FoldChange, 
##      log="x", pch=20, cex=.4, 
##      col = ifelse( res.eel$padj < .01, "red", "black" ),
##      main="My data")

## Populations

## scvPlot(cds.pop)

## residualsEcdfPlot( cds.pop, "EU" )
## residualsEcdfPlot( cds.pop, "TW" )

## plot( 
##      res.pop$baseMean, 
##      res.pop$log2FoldChange, 
##      log="x", pch=20, cex=.4, 
##      col = ifelse( res.pop$padj < .01, "red", "black" ),
##      main="Differences between populations")

@ 
